Traceback (most recent call last):
  File "/home/ubuntu/test-bigdata/adminmgr/media/code/A2/python/task/BD_649_692_1744_1808.py", line 2, in <module>
    file_location = str(sys.argv[1])
NameError: name 'sys' is not defined
